{% set name = "pynamodb" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pynamodb-{{ version }}.tar.gz
  sha256: c7d09700ace9f428e67ecf73fa867633c632de3acf402b2c7c136be695afda79

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - typing_extensions >=4
    - botocore >=1.12.54
    - python >={{ python_min }}
    - typing-extensions >=4

test:
  imports:
    - pynamodb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://jlafon.io/pynamodb.html
  summary: A Pythonic Interface to DynamoDB
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    PynamoDB is a Pythonic interface to Amazon’s DynamoDB. By using simple,
    yet powerful abstractions over the DynamoDB API, PynamoDB allows you
    to start developing immediately.
  doc_url: http://pynamodb.readthedocs.io/
  dev_url: https://github.com/pynamodb/PynamoDB

extra:
  recipe-maintainers:
    - sodre
    - BastianZim
